apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "api.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "api.fullname" . }}
          servicePort: 3002
        path: /helpers/
      - backend:
          serviceName: {{ template "api.fullname" . }}
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.host }}-tls

